# Generated by Django 6.0.2 on 2026-02-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('about', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=30, verbose_name='Контакты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Рабочие часы')),
                ('locate', models.URLField(verbose_name='Ссылка на карту')),
                ('instagram', models.URLField(verbose_name='Ссылка на инстаграм')),
                ('facebook', models.URLField(verbose_name='Ссылка на фейсбук')),
                ('youtube', models.URLField(verbose_name='Ссылка на ютуб')),
                ('whatsapp', models.URLField(verbose_name='Ссылка на ватсап')),
                ('telegram', models.URLField(verbose_name='Ссылка на телеграм')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компаниях',
            },
        ),
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('photo', models.ImageField(upload_to='myinfo/', verbose_name='Фото')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Моя информация',
                'verbose_name_plural': 'Мои данные',
            },
        ),
    ]
